### ISSUE TITLE
Route fails when starting on dead-end street with heading in location

### ISSUE THREAD

**Issue by noblige** [valhalla/thor#415]
Following request will fail as loki will only discover one directed edge. Expected behavior is to perform a U-Turn at the end of dead-end street.

`{"locations":[{"heading":295,"lat":23.561285,"lon":120.866005},{"lat":24.31249,"lon":120.52872}],"costing":"auto"}`

Location on the map:
https://www.openstreetmap.org/way/377619309

**Comment by dnesbitt61** [comment]
Will look into this. The fix may be a little tricky. I considered that we might need to allow U-turns at ends of dead-end streets. We mark nodes as dead-ends but actually need to mark directed edges as ending at a dead-end since we do not have the end node at the time of the costing Allowed method. But the harder problem is that we identify edges as "not_thru" and prune those to allow more efficient searches. We will need a way to bypass the pruning logic for these cases. 

We would know that the selected edge enters enters a not_thru set of edges and perhaps could select the opposing edge? Perhaps mark in the response that a U-turn is required?

**Comment by dnesbitt61** [comment]
As I thought, setting a deadend flag on the edge and allowing U-turns at dead-ends fixes this problem. However, the not_thru pruning does not fix other cases where the edge is not a dead-end, but leads to a dead-end. Will also need to come up with a strategy to enable/disable not_thru pruning.

**Comment by noblige** [comment]
@dnesbitt61 David, I think first part of the fix would be a great start, I imagine scenario where edge leads into dead-end edge should be relatively rare - I can run some queries and see how often that happens.

**Comment by dnesbitt61** [comment]
Added this capability a while ago. Lets open another issue if we see cases that are not properly handled.
